const actionTypes = {
  "LOGGEDIN_USER/DATA_FETCH_STARTED": "LOGGEDIN_USER/DATA_FETCH_STARTED",
  "LOGGEDIN_USER/DATA_FETCH_FAILURE": "LOGGEDIN_USER/DATA_FETCH_FAILURE",
  "LOGGEDIN_USER/DATA_FETCH_SUCCESS": "LOGGEDIN_USER/DATA_FETCH_SUCCESS",
  "LOGGEDIN_USER/CHANGE_HANDLE": "LOGGEDIN_USER/CHANGE_HANDLE",
  "LOGGEDIN_USER/UPDATE_TO_LOCALSTORE": "LOGGEDIN_USER/UPDATE_TO_LOCALSTORE",
  "LOGGEDIN_USER/UPDATE_DETAIL_FROM_LOCALSTORAGE": "LOGGEDIN_USER/UPDATE_DETAIL_FROM_LOCALSTORAGE",
  "LOGGEDIN_USER/CLOSE_CONFIRMATION_MODAL": "LOGGEDIN_USER/CLOSE_CONFIRMATION_MODAL",

  "SEARCHED_USERS/CHANGE_HANDLE": "SEARCHED_USERS/CHANGE_HANDLE",
  "SEARCHED_USERS/DATA_FETCH_STARTED": "SEARCHED_USERS/DATA_FETCH_STARTED",
  "SEARCHED_USERS/DATA_FETCH_SUCCESS": "SEARCHED_USERS/DATA_FETCH_SUCCESS",
  "SEARCHED_USERS/DATA_FETCH_FAILURE": "SEARCHED_USERS/DATA_FETCH_FAILURE",

  "SELECTED_USER/ADD_NEW": "SELECTED_USER/ADD_NEW"
};

module.exports = {
  actionTypes
};
