const actionTypes = {
  USER_DATA_FETCH_STARTED: 'USER_DATA_FETCH_STARTED',
  USER_DATA_FETCH_FAILURE: 'USER_DATA_FETCH_FAILURE',
  USER_DATA_FETCH_SUCCESS: 'USER_DATA_FETCH_SUCCESS'
};

module.exports = {
  actionTypes
}