const actionTypes = {
  "LOGGEDIN_USER/DATA_FETCH_STARTED": "LOGGEDIN_USER/DATA_FETCH_STARTED",
  "LOGGEDIN_USER/DATA_FETCH_FAILURE": "LOGGEDIN_USER/DATA_FETCH_FAILURE",
  "LOGGEDIN_USER/DATA_FETCH_SUCCESS": "LOGGEDIN_USER/DATA_FETCH_SUCCESS",
  "LOGGEDIN_USER/CHANGE_HANDLE": "LOGGEDIN_USER/CHANGE_HANDLE"
};

module.exports = {
  actionTypes
};
