const getUserData = () => ({
  login: "rnmKeshav",
  id: 11366455,
  node_id: "MDQ6VXNlcjExMzY2NDU1",
  avatar_url: "https://avatars1.githubusercontent.com/u/11366455?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/rnmKeshav",
  html_url: "https://github.com/rnmKeshav",
  followers_url: "https://api.github.com/users/rnmKeshav/followers",
  following_url: "https://api.github.com/users/rnmKeshav/following{/other_user}",
  gists_url: "https://api.github.com/users/rnmKeshav/gists{/gist_id}",
  starred_url: "https://api.github.com/users/rnmKeshav/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/rnmKeshav/subscriptions",
  organizations_url: "https://api.github.com/users/rnmKeshav/orgs",
  repos_url: "https://api.github.com/users/rnmKeshav/repos",
  events_url: "https://api.github.com/users/rnmKeshav/events{/privacy}",
  received_events_url: "https://api.github.com/users/rnmKeshav/received_events",
  type: "User",
  site_admin: false,
  name: "Keshav kumar",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  public_repos: 3,
  public_gists: 0,
  followers: 1,
  following: 0,
  created_at: "2015-03-07T16:49:12Z",
  updated_at: "2018-06-20T19:17:08Z"
});

const getSearchedUsers = () => ({
  total_count: 174,
  incomplete_results: false,
  items: [
    {
      login: "rnmp",
      id: 22627,
      node_id: "MDQ6VXNlcjIyNjI3",
      avatar_url: "https://avatars0.githubusercontent.com/u/22627?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmp",
      html_url: "https://github.com/rnmp",
      followers_url: "https://api.github.com/users/rnmp/followers",
      following_url: "https://api.github.com/users/rnmp/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmp/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmp/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmp/subscriptions",
      organizations_url: "https://api.github.com/users/rnmp/orgs",
      repos_url: "https://api.github.com/users/rnmp/repos",
      events_url: "https://api.github.com/users/rnmp/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmp/received_events",
      type: "User",
      site_admin: false,
      score: 32.814484
    },
    {
      login: "rNm",
      id: 58202,
      node_id: "MDQ6VXNlcjU4MjAy",
      avatar_url: "https://avatars1.githubusercontent.com/u/58202?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rNm",
      html_url: "https://github.com/rNm",
      followers_url: "https://api.github.com/users/rNm/followers",
      following_url: "https://api.github.com/users/rNm/following{/other_user}",
      gists_url: "https://api.github.com/users/rNm/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rNm/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rNm/subscriptions",
      organizations_url: "https://api.github.com/users/rNm/orgs",
      repos_url: "https://api.github.com/users/rNm/repos",
      events_url: "https://api.github.com/users/rNm/events{/privacy}",
      received_events_url: "https://api.github.com/users/rNm/received_events",
      type: "User",
      site_admin: false,
      score: 23.45999
    },
    {
      login: "ramonmedeiros",
      id: 950160,
      node_id: "MDQ6VXNlcjk1MDE2MA==",
      avatar_url: "https://avatars3.githubusercontent.com/u/950160?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ramonmedeiros",
      html_url: "https://github.com/ramonmedeiros",
      followers_url: "https://api.github.com/users/ramonmedeiros/followers",
      following_url: "https://api.github.com/users/ramonmedeiros/following{/other_user}",
      gists_url: "https://api.github.com/users/ramonmedeiros/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ramonmedeiros/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ramonmedeiros/subscriptions",
      organizations_url: "https://api.github.com/users/ramonmedeiros/orgs",
      repos_url: "https://api.github.com/users/ramonmedeiros/repos",
      events_url: "https://api.github.com/users/ramonmedeiros/events{/privacy}",
      received_events_url: "https://api.github.com/users/ramonmedeiros/received_events",
      type: "User",
      site_admin: false,
      score: 21.389814
    },
    {
      login: "RNMJD",
      id: 11294564,
      node_id: "MDQ6VXNlcjExMjk0NTY0",
      avatar_url: "https://avatars1.githubusercontent.com/u/11294564?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/RNMJD",
      html_url: "https://github.com/RNMJD",
      followers_url: "https://api.github.com/users/RNMJD/followers",
      following_url: "https://api.github.com/users/RNMJD/following{/other_user}",
      gists_url: "https://api.github.com/users/RNMJD/gists{/gist_id}",
      starred_url: "https://api.github.com/users/RNMJD/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/RNMJD/subscriptions",
      organizations_url: "https://api.github.com/users/RNMJD/orgs",
      repos_url: "https://api.github.com/users/RNMJD/repos",
      events_url: "https://api.github.com/users/RNMJD/events{/privacy}",
      received_events_url: "https://api.github.com/users/RNMJD/received_events",
      type: "User",
      site_admin: false,
      score: 18.186848
    },
    {
      login: "RNm-dove",
      id: 25113191,
      node_id: "MDQ6VXNlcjI1MTEzMTkx",
      avatar_url: "https://avatars3.githubusercontent.com/u/25113191?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/RNm-dove",
      html_url: "https://github.com/RNm-dove",
      followers_url: "https://api.github.com/users/RNm-dove/followers",
      following_url: "https://api.github.com/users/RNm-dove/following{/other_user}",
      gists_url: "https://api.github.com/users/RNm-dove/gists{/gist_id}",
      starred_url: "https://api.github.com/users/RNm-dove/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/RNm-dove/subscriptions",
      organizations_url: "https://api.github.com/users/RNm-dove/orgs",
      repos_url: "https://api.github.com/users/RNm-dove/repos",
      events_url: "https://api.github.com/users/RNm-dove/events{/privacy}",
      received_events_url: "https://api.github.com/users/RNm-dove/received_events",
      type: "User",
      site_admin: false,
      score: 16.22247
    },
    {
      login: "rnmessick",
      id: 18273031,
      node_id: "MDQ6VXNlcjE4MjczMDMx",
      avatar_url: "https://avatars3.githubusercontent.com/u/18273031?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmessick",
      html_url: "https://github.com/rnmessick",
      followers_url: "https://api.github.com/users/rnmessick/followers",
      following_url: "https://api.github.com/users/rnmessick/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmessick/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmessick/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmessick/subscriptions",
      organizations_url: "https://api.github.com/users/rnmessick/orgs",
      repos_url: "https://api.github.com/users/rnmessick/repos",
      events_url: "https://api.github.com/users/rnmessick/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmessick/received_events",
      type: "User",
      site_admin: false,
      score: 15.544891
    },
    {
      login: "RnmX",
      id: 12515340,
      node_id: "MDQ6VXNlcjEyNTE1MzQw",
      avatar_url: "https://avatars2.githubusercontent.com/u/12515340?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/RnmX",
      html_url: "https://github.com/RnmX",
      followers_url: "https://api.github.com/users/RnmX/followers",
      following_url: "https://api.github.com/users/RnmX/following{/other_user}",
      gists_url: "https://api.github.com/users/RnmX/gists{/gist_id}",
      starred_url: "https://api.github.com/users/RnmX/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/RnmX/subscriptions",
      organizations_url: "https://api.github.com/users/RnmX/orgs",
      repos_url: "https://api.github.com/users/RnmX/repos",
      events_url: "https://api.github.com/users/RnmX/events{/privacy}",
      received_events_url: "https://api.github.com/users/RnmX/received_events",
      type: "User",
      site_admin: false,
      score: 13.907572
    },
    {
      login: "rnmanhon",
      id: 16438085,
      node_id: "MDQ6VXNlcjE2NDM4MDg1",
      avatar_url: "https://avatars3.githubusercontent.com/u/16438085?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmanhon",
      html_url: "https://github.com/rnmanhon",
      followers_url: "https://api.github.com/users/rnmanhon/followers",
      following_url: "https://api.github.com/users/rnmanhon/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmanhon/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmanhon/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmanhon/subscriptions",
      organizations_url: "https://api.github.com/users/rnmanhon/orgs",
      repos_url: "https://api.github.com/users/rnmanhon/repos",
      events_url: "https://api.github.com/users/rnmanhon/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmanhon/received_events",
      type: "User",
      site_admin: false,
      score: 13.032562
    },
    {
      login: "rnml",
      id: 1153129,
      node_id: "MDQ6VXNlcjExNTMxMjk=",
      avatar_url: "https://avatars3.githubusercontent.com/u/1153129?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnml",
      html_url: "https://github.com/rnml",
      followers_url: "https://api.github.com/users/rnml/followers",
      following_url: "https://api.github.com/users/rnml/following{/other_user}",
      gists_url: "https://api.github.com/users/rnml/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnml/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnml/subscriptions",
      organizations_url: "https://api.github.com/users/rnml/orgs",
      repos_url: "https://api.github.com/users/rnml/repos",
      events_url: "https://api.github.com/users/rnml/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnml/received_events",
      type: "User",
      site_admin: false,
      score: 12.221944
    },
    {
      login: "rnmoge",
      id: 10771540,
      node_id: "MDQ6VXNlcjEwNzcxNTQw",
      avatar_url: "https://avatars0.githubusercontent.com/u/10771540?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmoge",
      html_url: "https://github.com/rnmoge",
      followers_url: "https://api.github.com/users/rnmoge/followers",
      following_url: "https://api.github.com/users/rnmoge/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmoge/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmoge/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmoge/subscriptions",
      organizations_url: "https://api.github.com/users/rnmoge/orgs",
      repos_url: "https://api.github.com/users/rnmoge/repos",
      events_url: "https://api.github.com/users/rnmoge/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmoge/received_events",
      type: "User",
      site_admin: false,
      score: 12.1201
    },
    {
      login: "rnmano",
      id: 5446919,
      node_id: "MDQ6VXNlcjU0NDY5MTk=",
      avatar_url: "https://avatars3.githubusercontent.com/u/5446919?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmano",
      html_url: "https://github.com/rnmano",
      followers_url: "https://api.github.com/users/rnmano/followers",
      following_url: "https://api.github.com/users/rnmano/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmano/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmano/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmano/subscriptions",
      organizations_url: "https://api.github.com/users/rnmano/orgs",
      repos_url: "https://api.github.com/users/rnmano/repos",
      events_url: "https://api.github.com/users/rnmano/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmano/received_events",
      type: "User",
      site_admin: false,
      score: 11.985383
    },
    {
      login: "rnmisrahi",
      id: 2232674,
      node_id: "MDQ6VXNlcjIyMzI2NzQ=",
      avatar_url: "https://avatars1.githubusercontent.com/u/2232674?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmisrahi",
      html_url: "https://github.com/rnmisrahi",
      followers_url: "https://api.github.com/users/rnmisrahi/followers",
      following_url: "https://api.github.com/users/rnmisrahi/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmisrahi/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmisrahi/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmisrahi/subscriptions",
      organizations_url: "https://api.github.com/users/rnmisrahi/orgs",
      repos_url: "https://api.github.com/users/rnmisrahi/repos",
      events_url: "https://api.github.com/users/rnmisrahi/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmisrahi/received_events",
      type: "User",
      site_admin: false,
      score: 11.898123
    },
    {
      login: "rnmourao",
      id: 16841587,
      node_id: "MDQ6VXNlcjE2ODQxNTg3",
      avatar_url: "https://avatars0.githubusercontent.com/u/16841587?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmourao",
      html_url: "https://github.com/rnmourao",
      followers_url: "https://api.github.com/users/rnmourao/followers",
      following_url: "https://api.github.com/users/rnmourao/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmourao/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmourao/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmourao/subscriptions",
      organizations_url: "https://api.github.com/users/rnmourao/orgs",
      repos_url: "https://api.github.com/users/rnmourao/repos",
      events_url: "https://api.github.com/users/rnmourao/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmourao/received_events",
      type: "User",
      site_admin: false,
      score: 11.807279
    },
    {
      login: "RNM49",
      id: 7226616,
      node_id: "MDQ6VXNlcjcyMjY2MTY=",
      avatar_url: "https://avatars3.githubusercontent.com/u/7226616?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/RNM49",
      html_url: "https://github.com/RNM49",
      followers_url: "https://api.github.com/users/RNM49/followers",
      following_url: "https://api.github.com/users/RNM49/following{/other_user}",
      gists_url: "https://api.github.com/users/RNM49/gists{/gist_id}",
      starred_url: "https://api.github.com/users/RNM49/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/RNM49/subscriptions",
      organizations_url: "https://api.github.com/users/RNM49/orgs",
      repos_url: "https://api.github.com/users/RNM49/repos",
      events_url: "https://api.github.com/users/RNM49/events{/privacy}",
      received_events_url: "https://api.github.com/users/RNM49/received_events",
      type: "User",
      site_admin: false,
      score: 11.473709
    },
    {
      login: "rnmontufar",
      id: 9203596,
      node_id: "MDQ6VXNlcjkyMDM1OTY=",
      avatar_url: "https://avatars3.githubusercontent.com/u/9203596?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmontufar",
      html_url: "https://github.com/rnmontufar",
      followers_url: "https://api.github.com/users/rnmontufar/followers",
      following_url: "https://api.github.com/users/rnmontufar/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmontufar/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmontufar/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmontufar/subscriptions",
      organizations_url: "https://api.github.com/users/rnmontufar/orgs",
      repos_url: "https://api.github.com/users/rnmontufar/repos",
      events_url: "https://api.github.com/users/rnmontufar/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmontufar/received_events",
      type: "User",
      site_admin: false,
      score: 11.391799
    },
    {
      login: "rnmeducation",
      id: 20966801,
      node_id: "MDQ6VXNlcjIwOTY2ODAx",
      avatar_url: "https://avatars3.githubusercontent.com/u/20966801?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmeducation",
      html_url: "https://github.com/rnmeducation",
      followers_url: "https://api.github.com/users/rnmeducation/followers",
      following_url: "https://api.github.com/users/rnmeducation/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmeducation/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmeducation/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmeducation/subscriptions",
      organizations_url: "https://api.github.com/users/rnmeducation/orgs",
      repos_url: "https://api.github.com/users/rnmeducation/repos",
      events_url: "https://api.github.com/users/rnmeducation/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmeducation/received_events",
      type: "User",
      site_admin: false,
      score: 11.177463
    },
    {
      login: "rnmendoza",
      id: 13860512,
      node_id: "MDQ6VXNlcjEzODYwNTEy",
      avatar_url: "https://avatars2.githubusercontent.com/u/13860512?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmendoza",
      html_url: "https://github.com/rnmendoza",
      followers_url: "https://api.github.com/users/rnmendoza/followers",
      following_url: "https://api.github.com/users/rnmendoza/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmendoza/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmendoza/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmendoza/subscriptions",
      organizations_url: "https://api.github.com/users/rnmendoza/orgs",
      repos_url: "https://api.github.com/users/rnmendoza/repos",
      events_url: "https://api.github.com/users/rnmendoza/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmendoza/received_events",
      type: "User",
      site_admin: false,
      score: 11.173383
    },
    {
      login: "RnMss",
      id: 859740,
      node_id: "MDQ6VXNlcjg1OTc0MA==",
      avatar_url: "https://avatars3.githubusercontent.com/u/859740?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/RnMss",
      html_url: "https://github.com/RnMss",
      followers_url: "https://api.github.com/users/RnMss/followers",
      following_url: "https://api.github.com/users/RnMss/following{/other_user}",
      gists_url: "https://api.github.com/users/RnMss/gists{/gist_id}",
      starred_url: "https://api.github.com/users/RnMss/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/RnMss/subscriptions",
      organizations_url: "https://api.github.com/users/RnMss/orgs",
      repos_url: "https://api.github.com/users/RnMss/repos",
      events_url: "https://api.github.com/users/RnMss/events{/privacy}",
      received_events_url: "https://api.github.com/users/RnMss/received_events",
      type: "User",
      site_admin: false,
      score: 10.936673
    },
    {
      login: "rabindramarndi1",
      id: 30542600,
      node_id: "MDQ6VXNlcjMwNTQyNjAw",
      avatar_url: "https://avatars3.githubusercontent.com/u/30542600?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rabindramarndi1",
      html_url: "https://github.com/rabindramarndi1",
      followers_url: "https://api.github.com/users/rabindramarndi1/followers",
      following_url: "https://api.github.com/users/rabindramarndi1/following{/other_user}",
      gists_url: "https://api.github.com/users/rabindramarndi1/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rabindramarndi1/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rabindramarndi1/subscriptions",
      organizations_url: "https://api.github.com/users/rabindramarndi1/orgs",
      repos_url: "https://api.github.com/users/rabindramarndi1/repos",
      events_url: "https://api.github.com/users/rabindramarndi1/events{/privacy}",
      received_events_url: "https://api.github.com/users/rabindramarndi1/received_events",
      type: "User",
      site_admin: false,
      score: 10.788766
    },
    {
      login: "rnmaconeghy",
      id: 6450830,
      node_id: "MDQ6VXNlcjY0NTA4MzA=",
      avatar_url: "https://avatars0.githubusercontent.com/u/6450830?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmaconeghy",
      html_url: "https://github.com/rnmaconeghy",
      followers_url: "https://api.github.com/users/rnmaconeghy/followers",
      following_url: "https://api.github.com/users/rnmaconeghy/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmaconeghy/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmaconeghy/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmaconeghy/subscriptions",
      organizations_url: "https://api.github.com/users/rnmaconeghy/orgs",
      repos_url: "https://api.github.com/users/rnmaconeghy/repos",
      events_url: "https://api.github.com/users/rnmaconeghy/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmaconeghy/received_events",
      type: "User",
      site_admin: false,
      score: 10.389736
    },
    {
      login: "rnmcdowell95",
      id: 25427294,
      node_id: "MDQ6VXNlcjI1NDI3Mjk0",
      avatar_url: "https://avatars1.githubusercontent.com/u/25427294?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmcdowell95",
      html_url: "https://github.com/rnmcdowell95",
      followers_url: "https://api.github.com/users/rnmcdowell95/followers",
      following_url: "https://api.github.com/users/rnmcdowell95/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmcdowell95/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmcdowell95/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmcdowell95/subscriptions",
      organizations_url: "https://api.github.com/users/rnmcdowell95/orgs",
      repos_url: "https://api.github.com/users/rnmcdowell95/repos",
      events_url: "https://api.github.com/users/rnmcdowell95/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmcdowell95/received_events",
      type: "User",
      site_admin: false,
      score: 10.3849535
    },
    {
      login: "rnmurray",
      id: 26361162,
      node_id: "MDQ6VXNlcjI2MzYxMTYy",
      avatar_url: "https://avatars2.githubusercontent.com/u/26361162?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmurray",
      html_url: "https://github.com/rnmurray",
      followers_url: "https://api.github.com/users/rnmurray/followers",
      following_url: "https://api.github.com/users/rnmurray/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmurray/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmurray/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmurray/subscriptions",
      organizations_url: "https://api.github.com/users/rnmurray/orgs",
      repos_url: "https://api.github.com/users/rnmurray/repos",
      events_url: "https://api.github.com/users/rnmurray/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmurray/received_events",
      type: "User",
      site_admin: false,
      score: 10.3849535
    },
    {
      login: "Rnmkr",
      id: 29107913,
      node_id: "MDQ6VXNlcjI5MTA3OTEz",
      avatar_url: "https://avatars3.githubusercontent.com/u/29107913?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Rnmkr",
      html_url: "https://github.com/Rnmkr",
      followers_url: "https://api.github.com/users/Rnmkr/followers",
      following_url: "https://api.github.com/users/Rnmkr/following{/other_user}",
      gists_url: "https://api.github.com/users/Rnmkr/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Rnmkr/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Rnmkr/subscriptions",
      organizations_url: "https://api.github.com/users/Rnmkr/orgs",
      repos_url: "https://api.github.com/users/Rnmkr/repos",
      events_url: "https://api.github.com/users/Rnmkr/events{/privacy}",
      received_events_url: "https://api.github.com/users/Rnmkr/received_events",
      type: "User",
      site_admin: false,
      score: 10.279779
    },
    {
      login: "rnmarkel",
      id: 17100915,
      node_id: "MDQ6VXNlcjE3MTAwOTE1",
      avatar_url: "https://avatars0.githubusercontent.com/u/17100915?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmarkel",
      html_url: "https://github.com/rnmarkel",
      followers_url: "https://api.github.com/users/rnmarkel/followers",
      following_url: "https://api.github.com/users/rnmarkel/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmarkel/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmarkel/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmarkel/subscriptions",
      organizations_url: "https://api.github.com/users/rnmarkel/orgs",
      repos_url: "https://api.github.com/users/rnmarkel/repos",
      events_url: "https://api.github.com/users/rnmarkel/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmarkel/received_events",
      type: "User",
      site_admin: false,
      score: 10.097786
    },
    {
      login: "rnm-patel",
      id: 28841217,
      node_id: "MDQ6VXNlcjI4ODQxMjE3",
      avatar_url: "https://avatars0.githubusercontent.com/u/28841217?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnm-patel",
      html_url: "https://github.com/rnm-patel",
      followers_url: "https://api.github.com/users/rnm-patel/followers",
      following_url: "https://api.github.com/users/rnm-patel/following{/other_user}",
      gists_url: "https://api.github.com/users/rnm-patel/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnm-patel/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnm-patel/subscriptions",
      organizations_url: "https://api.github.com/users/rnm-patel/orgs",
      repos_url: "https://api.github.com/users/rnm-patel/repos",
      events_url: "https://api.github.com/users/rnm-patel/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnm-patel/received_events",
      type: "User",
      site_admin: false,
      score: 10.045702
    },
    {
      login: "rnmrheinneckar",
      id: 7668661,
      node_id: "MDQ6VXNlcjc2Njg2NjE=",
      avatar_url: "https://avatars3.githubusercontent.com/u/7668661?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmrheinneckar",
      html_url: "https://github.com/rnmrheinneckar",
      followers_url: "https://api.github.com/users/rnmrheinneckar/followers",
      following_url: "https://api.github.com/users/rnmrheinneckar/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmrheinneckar/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmrheinneckar/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmrheinneckar/subscriptions",
      organizations_url: "https://api.github.com/users/rnmrheinneckar/orgs",
      repos_url: "https://api.github.com/users/rnmrheinneckar/repos",
      events_url: "https://api.github.com/users/rnmrheinneckar/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmrheinneckar/received_events",
      type: "User",
      site_admin: false,
      score: 9.941061
    },
    {
      login: "rnmkr2012",
      id: 8446853,
      node_id: "MDQ6VXNlcjg0NDY4NTM=",
      avatar_url: "https://avatars3.githubusercontent.com/u/8446853?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmkr2012",
      html_url: "https://github.com/rnmkr2012",
      followers_url: "https://api.github.com/users/rnmkr2012/followers",
      following_url: "https://api.github.com/users/rnmkr2012/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmkr2012/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmkr2012/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmkr2012/subscriptions",
      organizations_url: "https://api.github.com/users/rnmkr2012/orgs",
      repos_url: "https://api.github.com/users/rnmkr2012/repos",
      events_url: "https://api.github.com/users/rnmkr2012/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmkr2012/received_events",
      type: "User",
      site_admin: false,
      score: 9.564308
    },
    {
      login: "rnmaggott",
      id: 7803619,
      node_id: "MDQ6VXNlcjc4MDM2MTk=",
      avatar_url: "https://avatars1.githubusercontent.com/u/7803619?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmaggott",
      html_url: "https://github.com/rnmaggott",
      followers_url: "https://api.github.com/users/rnmaggott/followers",
      following_url: "https://api.github.com/users/rnmaggott/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmaggott/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmaggott/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmaggott/subscriptions",
      organizations_url: "https://api.github.com/users/rnmaggott/orgs",
      repos_url: "https://api.github.com/users/rnmaggott/repos",
      events_url: "https://api.github.com/users/rnmaggott/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmaggott/received_events",
      type: "User",
      site_admin: false,
      score: 9.405982
    },
    {
      login: "RNMaximo",
      id: 32446210,
      node_id: "MDQ6VXNlcjMyNDQ2MjEw",
      avatar_url: "https://avatars0.githubusercontent.com/u/32446210?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/RNMaximo",
      html_url: "https://github.com/RNMaximo",
      followers_url: "https://api.github.com/users/RNMaximo/followers",
      following_url: "https://api.github.com/users/RNMaximo/following{/other_user}",
      gists_url: "https://api.github.com/users/RNMaximo/gists{/gist_id}",
      starred_url: "https://api.github.com/users/RNMaximo/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/RNMaximo/subscriptions",
      organizations_url: "https://api.github.com/users/RNMaximo/orgs",
      repos_url: "https://api.github.com/users/RNMaximo/repos",
      events_url: "https://api.github.com/users/RNMaximo/events{/privacy}",
      received_events_url: "https://api.github.com/users/RNMaximo/received_events",
      type: "User",
      site_admin: false,
      score: 9.382174
    },
    {
      login: "rnmishra1",
      id: 26450749,
      node_id: "MDQ6VXNlcjI2NDUwNzQ5",
      avatar_url: "https://avatars0.githubusercontent.com/u/26450749?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rnmishra1",
      html_url: "https://github.com/rnmishra1",
      followers_url: "https://api.github.com/users/rnmishra1/followers",
      following_url: "https://api.github.com/users/rnmishra1/following{/other_user}",
      gists_url: "https://api.github.com/users/rnmishra1/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rnmishra1/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rnmishra1/subscriptions",
      organizations_url: "https://api.github.com/users/rnmishra1/orgs",
      repos_url: "https://api.github.com/users/rnmishra1/repos",
      events_url: "https://api.github.com/users/rnmishra1/events{/privacy}",
      received_events_url: "https://api.github.com/users/rnmishra1/received_events",
      type: "User",
      site_admin: false,
      score: 9.360835
    }
  ]
});

module.exports = {
  getUserData,
  getSearchedUsers
};
